Repository petlab-dev/app-prototype, pull requests merged in 2020-07, with the labels that each got.

#14 Fe/feature/issue 12
  FE/package-lock.json
  FE/package.json
  FE/storybook/stories/JyeongMu/src/components/loginClosingMent.jsx
  FE/storybook/stories/JyeongMu/src/components/loginHeader.jsx
  FE/storybook/stories/JyeongMu/src/components/loginSelectButton.jsx
  FE/storybook/stories/JyeongMu/src/screen/login.jsx
  FE/storybook/stories/JyeongMu/src/style/style.jsx
  FE/storybook/stories/index.jsx
Labels: : FE, flow: do not merge, type: bug, type: fix, type: research

#16 Apply Emotion to Login page
  FE/package-lock.json
  FE/package.json
  FE/storybook/stories/Button/index.android.jsx
  FE/storybook/stories/Button/index.ios.jsx
  FE/storybook/stories/Button/index.jsx
  FE/storybook/stories/CenterView/index.jsx
  FE/storybook/stories/CenterView/style.js
  FE/storybook/stories/JyeongMu/src/components/PreSignUpClosingMent.jsx
  FE/storybook/stories/JyeongMu/src/components/PreSignUpHeader.jsx
  FE/storybook/stories/JyeongMu/src/components/PreSignUpSelectButton.jsx
  FE/storybook/stories/JyeongMu/src/components/loginClosingMent.jsx
  FE/storybook/stories/JyeongMu/src/components/loginHeader.jsx
  FE/storybook/stories/JyeongMu/src/components/loginSelectButton.jsx
  FE/storybook/stories/JyeongMu/src/screen/login.jsx
  FE/storybook/stories/JyeongMu/src/screens/PreSignUp.jsx
  FE/storybook/stories/JyeongMu/src/style/style.jsx
  FE/storybook/stories/JyeongMu/src/styles.js
  FE/storybook/stories/Welcome/index.jsx
  FE/storybook/stories/Welcome/style.js
  FE/storybook/stories/components/Something.jsx
  FE/storybook/stories/index.jsx
  FE/yarn.lock
Labels: : FE, flow: to be reviewed

#13 [#10] feat: 로그인화면 견본 완성
  FE/package-lock.json
  FE/package.json
  FE/storybook/stories/Login/emotionStyle.js
  FE/storybook/stories/Login/iconButton.jsx
  FE/storybook/stories/Login/index.jsx
  FE/storybook/stories/Login/topText.jsx
  FE/storybook/stories/index.jsx
  node_modules/.yarn-integrity
  yarn.lock
Labels: : FE, flow: to be reviewed, type: feature

#24 [FE] 반려동물 등록 및 동물병원 정보 페이지 구현
  FE/package-lock.json
  FE/package.json
  FE/storybook/stories/JyeongMu/src/assets/PetEnroll.png
  FE/storybook/stories/JyeongMu/src/components/HomeAnimalEnrollment.jsx
  FE/storybook/stories/JyeongMu/src/components/HomeHeader.jsx
  FE/storybook/stories/JyeongMu/src/components/HomeHospital.jsx
  FE/storybook/stories/JyeongMu/src/components/HomeSearch.jsx
  FE/storybook/stories/JyeongMu/src/components/PreSignUpHeader.jsx
  FE/storybook/stories/JyeongMu/src/components/PreSignUpSelectButton.jsx
  FE/storybook/stories/JyeongMu/src/screens/Home.jsx
  FE/storybook/stories/JyeongMu/src/styles.js
  FE/storybook/stories/index.jsx
  FE/yarn.lock
Labels: : FE, flow: to be reviewed, type: fix
